name: "Release container images"
on:
  push:
    tags:
      - '*'
permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  container-release:
    runs-on: ubuntu-latest
    if: github.repository == 'letsblockit/letsblockit'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: cachix/install-nix-action@daddc62a2e67d1decb56e028c9fa68344b9b7c2a
      - name: Build container images
        run: |
          nix build .#render-container && ./result | docker load
          nix build .#server-container && ./result | docker load
      - name: Login to GHCR
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push tagged
        run: |
          docker tag ghcr.io/letsblockit/render:latest ghcr.io/letsblockit/render:$GITHUB_REF_NAME
          docker push ghcr.io/letsblockit/render:$GITHUB_REF_NAME
          docker tag ghcr.io/letsblockit/server:latest ghcr.io/letsblockit/server:$GITHUB_REF_NAME
          docker push ghcr.io/letsblockit/server:$GITHUB_REF_NAME
      - name: Push latest
        if: ${{ github.ref_type == 'tag' }}
        run: |
          docker push ghcr.io/letsblockit/render:latest
          docker push ghcr.io/letsblockit/server:latest
