name: "Reset staging to main"
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  reset:
    permissions:
      contents: write  # for Git to git push
    runs-on: ubuntu-latest
    if: github.repository == 'letsblockit/letsblockit'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - run: git push origin main:staging --force
